# Generated by Django 4.2.2 on 2023-07-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_finder",
            name="date_of_birth",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
