# Generated by Django 4.2.3 on 2023-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_disliked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
    ]
