# Generated by Django 4.2.2 on 2023-07-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_job_finder_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_finder",
            name="gender",
            field=models.CharField(max_length=100),
        ),
    ]
