# Generated by Django 4.2.2 on 2023-08-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_dashboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="is_comment",
        ),
        migrations.RemoveField(
            model_name="report",
            name="reported_comment",
        ),
    ]
