# Generated by Django 4.2.3 on 2023-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_post_is_disliked_post_is_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_disliked",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_liked",
            field=models.BooleanField(default=True),
        ),
    ]
