# Generated by Django 4.2.2 on 2023-08-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_report_is_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='status',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='job_applied',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='job_finder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.job_finder'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status_E',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied'), ('HIDE', 'Hide'), ('HIGHTLIGHT', 'Hightlight')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status_JF',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
        migrations.DeleteModel(
            name='ApplicationHistory',
        ),
    ]
