# Generated by Django 4.2.2 on 2023-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_introduction_alter_post_is_disliked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
