# Generated by Django 4.2.2 on 2023-08-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_report_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reported_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.comment",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.post",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
