# Generated by Django 4.2.2 on 2023-08-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_report_reported_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_applied', models.CharField(max_length=200)),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('job_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_finder')),
            ],
        ),
    ]
