# Generated by Django 4.2.2 on 2023-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
