# Generated by Django 4.2.2 on 2023-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.URLField(blank=True),
        ),
    ]
