# Generated by Django 4.2.2 on 2023-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
